gui:
  language: "en"
  useHunkModeInStagingView: false
  theme:
    selectedLineBgColor:
      - "#444444"
git:
  log:
    showWholeGraph: true
os:
  edit: 'codium --goto {{filename}}'
  editAtLine: 'codium --goto {{filename}}:{{line}}'
  editAtLineAndWait: 'codium --goto --wait {{filename}}:{{line}}'
  editInTerminal: false
  openDirInEditor: 'codium {{dir}}'
customCommands:
  - key: "A"
    command: git commit --amend {{.Form.V}} --no-edit
    context: "files"
    description: "Amend commit"
    prompts:
      - type: "menu"
        title: "Need verify ?"
        key: "V"
        options:
          - value: " "
            name: "Verify"
          - value: --no-verify
            name: "Skip"
  - key: "F"
    context: remotes
    command: "git fetch --prune origin --verbose"
    description: "Fetch remote branches"
